tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),


]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
	url(r'^$', views.index, name='index'),
	url(r'^rango/', include('rango.urls')),
	url(r'^admin/', admin.site.urls),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from __future__ import unicode_literals
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	
	slug = models.SlugField(unique=True)
	def save(self, *args, **kwargs):
		self.slug =slugify(self.name)
		super(Category, self).save(*args, **kwargs)
	class Meta:
		verbose_name_plural = 'Categories'
        
	def __str__(self):
		return self.name
		
		
class Page(models.Model):
	category=models.ForeignKey(Category)
	title =models.CharField(max_length=128)
	url=models.URLField()
	views=models.IntegerField(default=0)
	
	def __str__(self): # for python 2, use_unicode_too
		return self.title
		 
class Age(models.Model):
	name=models.CharField(max_length=128)

	def __str__(self):
		return self.name


class UserProfile(models.Model):
	# This line is required. Links UserProfile to a User model instance.
	user = models.OneToOneField(User)
	# The additional attributes we wish to include.
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)
	# Override the __unicode__() method to return out something meaningful!
	# Remember if you use Python 2.7.x, define __unicode__ too!
	def __str__(self):
		return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page,Category,UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name=forms.CharField(max_length=128,
                         help_text="Please enter the category name.")
    views=forms.IntegerField(widget=forms.HiddenInput(), initial =0)
    likes =forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    slug =forms.CharField(widget=forms.HiddenInput(), required= False)

    class Meta:
        model=Category
        fields =('name' ,)
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="please enter the title of the page.")
    url=forms.URLField(max_length=200,
                       help_text="Please enter the URL of the page.")
    views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    class Meta:
        model=Page
        exclude=('category' ,)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta:
        model =User
        fields=('username', 'email','password')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from django.core.urlresolvers import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate,login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime




def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context=context_dict)
    return response

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1

        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1

        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits



def about(request):
    visitor_cookie_handler(request)
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    print(request.method)
    print(request.user)

    context_dict['visits'] = request.session['visits']
    response= render(request, 'rango/about.html', {})
    return response

def show_category(request, category_name_slug):
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

        # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)
def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # if the two forms are valid..
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)

    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                'rango/register.html',
                {'user_form': user_form,
                'profile_form': profile_form,
                'registered': registered})
def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html', {})
@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{load staticfiles %}
{%block title_block %}
	{{about.name}}
{% endblock %}

{% block body_block %}
	<p> visits: {{ visits }}</p>
	This tutorial has been put together by zhang ji
	<img src="{{MEDIA_URL}}cat.jpg" alt="picture of cat">

{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}

    <body>
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category"/>
        </form>
    </div>
    </body>

{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Rango - Add Page
{% endblock %}

{% block body_block %}


    {% if category %}

    <h1>Add a Page to {{ category.name }}</h1>

    <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}

        <input type="submit" name="submit" value="Add Page"/>
    </form>

    {% else %}
        The specified category does not exist!
    {% endif %}



{% endblock %}

tango_with_django_project/templates/rango/base.html
{% load rango_template_tags %}
{% load staticfiles %}

<html>


<head>
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>

<div>
    {% block sidebar_block %}
        {% get_category_list %}
    {% endblock %}
</div>


<div>
    {% block body_block %}
    {% endblock %}
</div>
<hr/>
<div>
    <ul>
    {% if user.is_authenticated %}
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'rango:logout' %}">Logout</a></li>
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>

    {%  else %}
        <li><a href = "{% url 'rango:register' %}">Sign Up</a></li>
        <li><a href="{% url 'rango:login' %}">Login</a></li>
    {%  endif %}

        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
</div>
</body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>

        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
       {% for c in cats %}
           {% if c == act_cat %}
               <li>
                   <strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong>
               </li>
           {% else %}
               <li>
                   <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
           {% endif %}
       {% endfor %}
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>

    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
    </div>
	<p>visits:{{visits}}</p>
    <div>
        {% if categories %}
            <h2>{{ "Most Liked Categories" }}</h2>
            <ul>
                {% for category in categories %}

                    <li>
                        <a href="{% url 'rango:show_category' category.slug %}">
                            {{ category.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if pages %}
            <h2>{{ "Most Viewed Pages" }}</h2>
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

    <div>
        <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango"/>

    </div>


{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register with Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display each form -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}


        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
     Restricted
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}